[package]
name = "remote-monitoring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
sysinfo = "0.29.10"
ssh2 = "0.9.4"
time = "0.3.30"
